# Generated by Django 4.2.4 on 2023-08-15 07:32

import carsuri.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Detail",
            fields=[
                ("detail_no", models.AutoField(primary_key=True, serialize=False)),
                (
                    "detail_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fileupload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("image", models.ImageField(upload_to=carsuri.models.date_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name="Maker",
            fields=[
                ("maker_no", models.AutoField(primary_key=True, serialize=False)),
                (
                    "maker_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                ("map_no", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("addr", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("tel", models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                ("model_no", models.AutoField(primary_key=True, serialize=False)),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "maker_num",
                    models.ForeignKey(
                        blank=True,
                        db_column="maker_num",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="carsuri.maker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepairCost",
            fields=[
                ("repair_cost_no", models.AutoField(primary_key=True, serialize=False)),
                ("cost", models.IntegerField(blank=True, null=True)),
                ("repair", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "detail_num",
                    models.ForeignKey(
                        blank=True,
                        db_column="detail_num",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="carsuri.detail",
                    ),
                ),
                (
                    "maker_num",
                    models.ForeignKey(
                        blank=True,
                        db_column="maker_num",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="carsuri.maker",
                    ),
                ),
                (
                    "model_num",
                    models.ForeignKey(
                        blank=True,
                        db_column="model_num",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="carsuri.model",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExchangeCost",
            fields=[
                (
                    "exchange_cost_no",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cost", models.IntegerField(blank=True, null=True)),
                ("exchange", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "detail_num",
                    models.ForeignKey(
                        blank=True,
                        db_column="detail_num",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="carsuri.detail",
                    ),
                ),
                (
                    "maker_num",
                    models.ForeignKey(
                        blank=True,
                        db_column="maker_num",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="carsuri.maker",
                    ),
                ),
                (
                    "model_num",
                    models.ForeignKey(
                        blank=True,
                        db_column="model_num",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="carsuri.model",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="detail",
            name="model_num",
            field=models.ForeignKey(
                blank=True,
                db_column="model_num",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="carsuri.model",
            ),
        ),
    ]
